// <auto-generated />
using System;
using LocoRealt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocoRealt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250814142318_FixColumnMappings")]
    partial class FixColumnMappings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocoRealt.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecondaryPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LocoRealt.Models.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryId"));

                    b.Property<bool>("IntShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LngSort")
                        .HasColumnType("int");

                    b.Property<string>("TxtTitle")
                        .IsRequired()
                        .HasMaxLength(1020)
                        .HasColumnType("nvarchar(1020)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LocoRealt.Models.City", b =>
                {
                    b.Property<long>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CityId"));

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IntPopular")
                        .HasColumnType("bit");

                    b.Property<bool>("IntShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<string>("TxtTitle")
                        .IsRequired()
                        .HasMaxLength(1020)
                        .HasColumnType("nvarchar(1020)");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("RegionId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("LocoRealt.Models.Country", b =>
                {
                    b.Property<long>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CountryId"));

                    b.Property<bool>("IntShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LngSort")
                        .HasColumnType("int");

                    b.Property<string>("TxtTitle")
                        .IsRequired()
                        .HasMaxLength(1020)
                        .HasColumnType("nvarchar(1020)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("LocoRealt.Models.Like", b =>
                {
                    b.Property<long>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LikeId"));

                    b.Property<DateTime?>("DtLiked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LikeId");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("LocoRealt.Models.Listing", b =>
                {
                    b.Property<long>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ListingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ListingId"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DblPrice")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime>("DtCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DtExpiry")
                        .HasColumnType("datetime");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("HasCentralHeating")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCentralSCanalisation")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCentralWater")
                        .HasColumnType("bit");

                    b.Property<bool>("HasGasHeating")
                        .HasColumnType("bit");

                    b.Property<bool>("HasInternet")
                        .HasColumnType("bit");

                    b.Property<bool>("HasParking")
                        .HasColumnType("bit");

                    b.Property<bool>("IntShow")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBargain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForRent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLongTerm")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LandArea")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<long>("ListingStatusId")
                        .HasColumnType("bigint");

                    b.Property<long>("ListingTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("MemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemSEODescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MemSEODescription");

                    b.Property<string>("MemSEOKeywords")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MemSEOKeywords");

                    b.Property<int?>("Rooms")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("SubCategoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TotalArea")
                        .HasColumnType("decimal(9, 2)");

                    b.Property<string>("TxtTitle")
                        .IsRequired()
                        .HasMaxLength(2040)
                        .HasColumnType("nvarchar(2040)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ListingId");

                    b.HasIndex("ListingStatusId");

                    b.HasIndex("ListingTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Listings_Category");

                    b.HasIndex(new[] { "DblPrice" }, "IX_Listings_Price");

                    b.HasIndex(new[] { "SubCategoryId" }, "IX_Listings_SubCategory");

                    b.ToTable("Listings", (string)null);
                });

            modelBuilder.Entity("LocoRealt.Models.ListingGeo", b =>
                {
                    b.Property<long>("ListingGeoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ListingGeoId"));

                    b.Property<long?>("CityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("DblLatitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("DblLongitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<DateTime?>("DtTimeStamp")
                        .HasColumnType("datetime");

                    b.Property<bool>("IntGoogleMap")
                        .HasColumnType("bit");

                    b.Property<long>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<string>("TxtAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListingGeoId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("ListingId")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("ListingGeos");
                });

            modelBuilder.Entity("LocoRealt.Models.ListingImage", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImageId"));

                    b.Property<int?>("IntSort")
                        .HasColumnType("int");

                    b.Property<long>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("TxtImage")
                        .HasMaxLength(2040)
                        .HasColumnType("nvarchar(2040)");

                    b.Property<string>("TxtImageTitle")
                        .HasMaxLength(2040)
                        .HasColumnType("nvarchar(2040)");

                    b.Property<string>("TxtImageUrl")
                        .HasMaxLength(2040)
                        .HasColumnType("nvarchar(2040)");

                    b.HasKey("ImageId");

                    b.HasIndex("ListingId");

                    b.ToTable("ListingImages");
                });

            modelBuilder.Entity("LocoRealt.Models.ListingStatus", b =>
                {
                    b.Property<long>("ListingStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ListingStatusId"));

                    b.Property<bool>("IntShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LngSort")
                        .HasColumnType("int");

                    b.Property<string>("TxtTitle")
                        .IsRequired()
                        .HasMaxLength(2040)
                        .HasColumnType("nvarchar(2040)");

                    b.HasKey("ListingStatusId");

                    b.ToTable("ListingStatuses");
                });

            modelBuilder.Entity("LocoRealt.Models.ListingType", b =>
                {
                    b.Property<long>("ListingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ListingTypeId"));

                    b.Property<bool>("IntShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LngSort")
                        .HasColumnType("int");

                    b.Property<string>("TxtTitle")
                        .IsRequired()
                        .HasMaxLength(2040)
                        .HasColumnType("nvarchar(2040)");

                    b.HasKey("ListingTypeId");

                    b.ToTable("ListingTypes");
                });

            modelBuilder.Entity("LocoRealt.Models.Region", b =>
                {
                    b.Property<long>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RegionId"));

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IntShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TxtTitle")
                        .IsRequired()
                        .HasMaxLength(1020)
                        .HasColumnType("nvarchar(1020)");

                    b.HasKey("RegionId");

                    b.HasIndex("CountryId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("LocoRealt.Models.SpecCommercial", b =>
                {
                    b.Property<long>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommercialListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Condition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FloorNum")
                        .HasColumnType("int");

                    b.Property<bool?>("HasHeating")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasSecurity")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasSewerage")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasWater")
                        .HasColumnType("bit");

                    b.Property<string>("Purpose")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TotalArea")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("TotalFloors")
                        .HasColumnType("int");

                    b.HasKey("ListingId");

                    b.HasIndex(new[] { "ListingId" }, "UQ_CommercialListings_ListingId")
                        .IsUnique();

                    b.ToTable("Spec_Commercial");
                });

            modelBuilder.Entity("LocoRealt.Models.SpecFlat", b =>
                {
                    b.Property<long>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Balcony")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BathroomType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("FlatId")
                        .HasColumnType("bigint");

                    b.Property<int?>("FloorNum")
                        .HasColumnType("int");

                    b.Property<string>("HeatingType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsRoom")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsStudio")
                        .HasColumnType("bit");

                    b.Property<decimal?>("KitchenArea")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<decimal?>("LivingArea")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("RepairState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Rooms")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalArea")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int?>("TotalFloors")
                        .HasColumnType("int");

                    b.Property<string>("WindowView")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ListingId");

                    b.HasIndex(new[] { "ListingId" }, "UQ_Flats_ListingId")
                        .IsUnique();

                    b.ToTable("Spec_Flats");
                });

            modelBuilder.Entity("LocoRealt.Models.SpecHouse", b =>
                {
                    b.Property<long>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Condition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FloorCount")
                        .HasColumnType("int");

                    b.Property<string>("Heating")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("HouseArea")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<long>("HouseListingId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("LandArea")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("LegalStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sewerage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WallMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WaterSupply")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ListingId");

                    b.HasIndex(new[] { "ListingId" }, "UQ_HouseListings_ListingId")
                        .IsUnique();

                    b.ToTable("Spec_Houses");
                });

            modelBuilder.Entity("LocoRealt.Models.SpecLandPlot", b =>
                {
                    b.Property<long>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("HasCentralWater")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasElectricity")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasGas")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasSeptic")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasWaterWell")
                        .HasColumnType("bit");

                    b.Property<long>("LandPlotListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Purpose")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ListingId");

                    b.HasIndex(new[] { "ListingId" }, "UQ_LandPlotListings_ListingId")
                        .IsUnique();

                    b.ToTable("Spec_LandPlots");
                });

            modelBuilder.Entity("LocoRealt.Models.SubCategory", b =>
                {
                    b.Property<long>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SubCategoryId"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IntShow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LngSort")
                        .HasColumnType("int");

                    b.Property<string>("TxtTitle")
                        .IsRequired()
                        .HasMaxLength(1020)
                        .HasColumnType("nvarchar(1020)");

                    b.HasKey("SubCategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LocoRealt.Models.City", b =>
                {
                    b.HasOne("LocoRealt.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired();

                    b.HasOne("LocoRealt.Models.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("LocoRealt.Models.Like", b =>
                {
                    b.HasOne("LocoRealt.Models.Listing", "Listing")
                        .WithMany("Likes")
                        .HasForeignKey("ListingId")
                        .IsRequired();

                    b.HasOne("LocoRealt.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LocoRealt.Models.Listing", b =>
                {
                    b.HasOne("LocoRealt.Models.Category", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocoRealt.Models.ListingStatus", "ListingStatus")
                        .WithMany("Listings")
                        .HasForeignKey("ListingStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocoRealt.Models.ListingType", "ListingType")
                        .WithMany("Listings")
                        .HasForeignKey("ListingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocoRealt.Models.SubCategory", "SubCategory")
                        .WithMany("Listings")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocoRealt.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("ListingStatus");

                    b.Navigation("ListingType");

                    b.Navigation("SubCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LocoRealt.Models.ListingGeo", b =>
                {
                    b.HasOne("LocoRealt.Models.City", "City")
                        .WithMany("ListingGeos")
                        .HasForeignKey("CityId");

                    b.HasOne("LocoRealt.Models.Country", "Country")
                        .WithMany("ListingGeos")
                        .HasForeignKey("CountryId");

                    b.HasOne("LocoRealt.Models.Listing", "Listing")
                        .WithOne("ListingGeo")
                        .HasForeignKey("LocoRealt.Models.ListingGeo", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocoRealt.Models.Region", "Region")
                        .WithMany("ListingGeos")
                        .HasForeignKey("RegionId");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Listing");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("LocoRealt.Models.ListingImage", b =>
                {
                    b.HasOne("LocoRealt.Models.Listing", "Listing")
                        .WithMany("ListingImages")
                        .HasForeignKey("ListingId")
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("LocoRealt.Models.Region", b =>
                {
                    b.HasOne("LocoRealt.Models.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("LocoRealt.Models.SpecCommercial", b =>
                {
                    b.HasOne("LocoRealt.Models.Listing", "Listing")
                        .WithOne("SpecCommercial")
                        .HasForeignKey("LocoRealt.Models.SpecCommercial", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("LocoRealt.Models.SpecFlat", b =>
                {
                    b.HasOne("LocoRealt.Models.Listing", "Listing")
                        .WithOne("SpecFlat")
                        .HasForeignKey("LocoRealt.Models.SpecFlat", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("LocoRealt.Models.SpecHouse", b =>
                {
                    b.HasOne("LocoRealt.Models.Listing", "Listing")
                        .WithOne("SpecHouse")
                        .HasForeignKey("LocoRealt.Models.SpecHouse", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("LocoRealt.Models.SpecLandPlot", b =>
                {
                    b.HasOne("LocoRealt.Models.Listing", "Listing")
                        .WithOne("SpecLandPlot")
                        .HasForeignKey("LocoRealt.Models.SpecLandPlot", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("LocoRealt.Models.SubCategory", b =>
                {
                    b.HasOne("LocoRealt.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LocoRealt.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LocoRealt.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocoRealt.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LocoRealt.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocoRealt.Models.Category", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("LocoRealt.Models.City", b =>
                {
                    b.Navigation("ListingGeos");
                });

            modelBuilder.Entity("LocoRealt.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("ListingGeos");

                    b.Navigation("Regions");
                });

            modelBuilder.Entity("LocoRealt.Models.Listing", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("ListingGeo");

                    b.Navigation("ListingImages");

                    b.Navigation("SpecCommercial");

                    b.Navigation("SpecFlat");

                    b.Navigation("SpecHouse");

                    b.Navigation("SpecLandPlot");
                });

            modelBuilder.Entity("LocoRealt.Models.ListingStatus", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("LocoRealt.Models.ListingType", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("LocoRealt.Models.Region", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("ListingGeos");
                });

            modelBuilder.Entity("LocoRealt.Models.SubCategory", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
